# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:
        - id: black
          name: Format with Black
          entry: poetry run black
          language: system
          types: [python]

        - id: ruff
          name: Format with Ruff
          entry: poetry run ruff check
          language: system
          types: [ python ]
          args: [ --fix, --exit-non-zero-on-fix, . ]

        - id: mypy
          name: Validate types with MyPy
          entry: poetry run mypy
          language: system
          types: [ python ]
          pass_filenames: false
          args: [ . ]
