# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
        # Ruff version.
      rev: 'v0.0.246'
      hooks:
          - id: ruff
            args: [ --fix, --exit-non-zero-on-fix ]

    - repo: https://github.com/ambv/black
      rev: 23.1.0
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.0.0'  # Use the sha / tag you want to point at
      hooks:
        - id: mypy
          args: [--install-types, --non-interactive]